Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"
	config.vm.provision "docker" do |d|
    	d.build_image "/vagrant/", args: "-t boozt:latest"
    	d.run "boozt:latest", args: "-p 80:80"
  	end
	config.vm.network :public_network, ip: "192.168.100.101", netmask: "24"
end